/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gov.va.semoss.ui.components;

import gov.va.semoss.om.SEMOSSVertex;
import gov.va.semoss.ui.components.playsheets.GraphPlaySheet;
import gov.va.semoss.ui.components.renderers.LabeledPairRenderer;
import gov.va.semoss.util.Utility;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import org.openrdf.model.URI;

/**
 *
 * @author ryan
 */
public class GraphCondensePanel extends javax.swing.JPanel {

	public static enum RemovalStrategy {

		KEEP, IGNORE
	};
	private final DefaultComboBoxModel<URI> nodetypemodel
			= new DefaultComboBoxModel<>();

	/**
	 * Creates new form GraphCondensePanel
	 */
	public GraphCondensePanel( GraphPlaySheet gps ) {
		initComponents();

		Set<URI> seen = new HashSet<>();
		for ( SEMOSSVertex v : gps.getVisibleGraph().getVertices() ) {
			URI type = v.getType();
			if ( !seen.contains( type ) ) {
				seen.add( type );
			}
		}

		Map<URI, String> labels = Utility.getInstanceLabels( seen, gps.getEngine() );
		labels = Utility.sortUrisByLabel( labels );

		for ( URI t : labels.keySet() ) {
			nodetypemodel.addElement( t );
		}

		LabeledPairRenderer<URI> renderer = LabeledPairRenderer.getUriPairRenderer();
		renderer.cache( labels );
		nodetype.setRenderer( renderer );
	}

	public URI getEdgeTypeToRemove() {
		return nodetype.getItemAt( nodetype.getSelectedIndex() );
	}

	public RemovalStrategy getRemovalStrategy() {
		return ( keeper.isSelected() ? RemovalStrategy.KEEP : RemovalStrategy.IGNORE );
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings( "unchecked" )
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup1 = new javax.swing.ButtonGroup();
    jLabel1 = new javax.swing.JLabel();
    nodetype = new javax.swing.JComboBox<URI>();
    jPanel1 = new javax.swing.JPanel();
    keeper = new javax.swing.JRadioButton();
    ignoreprop = new javax.swing.JRadioButton();

    jLabel1.setText("Remove Node Type");

    nodetype.setModel(nodetypemodel);

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(java.awt.Color.gray, 1, true), "On Edge Property Clash"));

    buttonGroup1.add(keeper);
    keeper.setSelected(true);
    keeper.setText("Keep All Values");

    buttonGroup1.add(ignoreprop);
    ignoreprop.setText("Ignore the Property");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(ignoreprop)
      .addComponent(keeper)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(keeper)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(ignoreprop))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(nodetype, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(nodetype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 127, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JRadioButton ignoreprop;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JRadioButton keeper;
  private javax.swing.JComboBox<URI> nodetype;
  // End of variables declaration//GEN-END:variables
}
