/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gov.va.semoss.ui.components;

import java.net.MalformedURLException;
import java.net.URL;

/**
 *
 * @author ryan
 */
public class RemoteDbPanel extends javax.swing.JPanel {

	public static final URL INTERNAL;

	static {
		URL temp;
		try {
			temp = new URL( "http://internal" );
		}
		catch ( Exception e ) {
			temp = null;
		}
		INTERNAL = temp;
	}

	/**
	 * Creates new form RemoteDbPanel
	 */
	public RemoteDbPanel( String ext, String inter ) {
		initComponents();

		remoteurl.setText( ext );

		insightsurl.setEnabled( true );
		insightsurl.setText( inter );
	}

	public URL getUrl() throws MalformedURLException {
		return new URL( remoteurl.getText() );
	}

	public URL getInsights() throws MalformedURLException {
		return new URL( insightsurl.getText() );
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings( "unchecked" )
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup1 = new javax.swing.ButtonGroup();
    jLabel1 = new javax.swing.JLabel();
    remoteurl = new javax.swing.JTextField();
    insightsurl = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();

    jLabel1.setText("Remote URL");

    insightsurl.setEnabled(false);

    jLabel2.setText("Insights URL");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
            .addGap(0, 0, 0))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(insightsurl, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
          .addComponent(remoteurl)))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1)
          .addComponent(remoteurl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(insightsurl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2)))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JTextField insightsurl;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JTextField remoteurl;
  // End of variables declaration//GEN-END:variables
}
