/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gov.va.semoss.ui.components;

import gov.va.semoss.rdf.engine.util.VocabularyRegistry;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.JCheckBox;

/**
 *
 * @author ryan
 */
public class VocabularyPanel extends javax.swing.JPanel {

	private final List<JCheckBox> vocabs = new ArrayList<>();

	/**
	 * Creates new form VocabularyPanel
	 */
	public VocabularyPanel() {
		initComponents();

		for ( Map.Entry<String, Boolean> en : VocabularyRegistry.getVocabularies2().entrySet() ) {
			JCheckBox jcb = new JCheckBox( en.getKey(), en.getValue() );
			vocabs.add( jcb );
			buttonpanel.add( jcb );
		}
		revalidate();
		repaint();
	}

	public List<URL> getSelectedVocabularies() {
		List<URL> urls = new ArrayList<>();
		for ( JCheckBox jcb : vocabs ) {
			if ( jcb.isSelected() ) {
				String label = jcb.getText();
				urls.add( VocabularyRegistry.getURL( label ) );
			}
		}

		return urls;
	}

	@Override
	public void setEnabled( boolean b ){
		super.setEnabled( b );
		for( JCheckBox jcb : vocabs ){
			jcb.setEnabled( b );
		}
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings( "unchecked" )
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    buttonpanel = new javax.swing.JPanel();

    jLabel1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
    jLabel1.setText("Reload Vocabularies (After Clear)");

    buttonpanel.setLayout(new javax.swing.BoxLayout(buttonpanel, javax.swing.BoxLayout.PAGE_AXIS));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addComponent(buttonpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(buttonpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel buttonpanel;
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
}
