/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gov.va.semoss.ui.components;

import gov.va.semoss.rdf.engine.util.VocabularyRegistry;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.JCheckBox;

/**
 *
 * @author ryan
 */
public class VocabularyPanel extends javax.swing.JPanel {

	private final List<JCheckBox> vocabs = new ArrayList<>();

	/**
	 * Creates new form VocabularyPanel
	 */
	public VocabularyPanel() {
		initComponents();

		for ( Map.Entry<String, Boolean> en : VocabularyRegistry.getVocabularies2().entrySet() ) {
			JCheckBox jcb = new JCheckBox( en.getKey(), en.getValue() );
			vocabs.add( jcb );
			add( jcb );
		}
		revalidate();
		repaint();
	}

	public List<URL> getSelectedVocabularies() {
		List<URL> urls = new ArrayList<>();
		for ( JCheckBox jcb : vocabs ) {
			if ( jcb.isSelected() ) {
				String label = jcb.getText();
				VocabularyRegistry.getURL( label );
			}
		}

		return urls;
	}

	@Override
	public void setEnabled( boolean b ){
		super.setEnabled( b );
		for( JCheckBox jcb : vocabs ){
			jcb.setEnabled( b );
		}
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings( "unchecked" )
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Add Vocabularies", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 12))); // NOI18N
    setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
