/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ostrichemulators.semtool.ui.components;

import com.ostrichemulators.semtool.rdf.engine.util.VocabularyRegistry;
import java.awt.Insets;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.JCheckBox;

/**
 *
 * @author ryan
 */
public class VocabularyDBPanel extends javax.swing.JPanel {
	
	private final List<JCheckBox> vocabs = new ArrayList<>();

	/**
	 * Creates new form VocabularyPanel
	 */
	public VocabularyDBPanel() {
		initComponents();
				
		for ( Map.Entry<String, Boolean> en : VocabularyRegistry.getVocabularies2().entrySet() ) {
			JCheckBox jcb = new JCheckBox( en.getKey(), en.getValue() );
			jcb.setMargin( new Insets( 2, 0, 2, 0 ) );
			vocabs.add( jcb );
			buttonpanel.add( jcb );
		}
		revalidate();
		repaint();
	}
	
	public List<URL> getSelectedVocabularies() {
		List<URL> urls = new ArrayList<>();
		for ( JCheckBox jcb : vocabs ) {
			if ( jcb.isSelected() ) {
				String label = jcb.getText();
				urls.add( VocabularyRegistry.getURL( label ) );
			}
		}
		
		return urls;
	}
	
	@Override
	public void setEnabled( boolean b ) {
		super.setEnabled( b );
		for ( JCheckBox jcb : vocabs ) {
			jcb.setEnabled( b );
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings( "unchecked" )
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    label = new javax.swing.JLabel();
    buttonpanel = new javax.swing.JPanel();
    filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 4), new java.awt.Dimension(0, 4), new java.awt.Dimension(1000, 4));
    filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));

    label.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
    label.setText("Import Vocabularies");
    label.setMaximumSize(null);
    buttonpanel.setLayout(new javax.swing.BoxLayout(buttonpanel, javax.swing.BoxLayout.PAGE_AXIS));
    buttonpanel.add(filler2);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
      .addComponent(buttonpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addGroup(layout.createSequentialGroup()
        .addGap(69, 69, 69)
        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
     //   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(buttonpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
    //    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
  //      .addContainerGap()
        )
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel buttonpanel;
  private javax.swing.Box.Filler filler1;
  private javax.swing.Box.Filler filler2;
  private javax.swing.JLabel label;
  // End of variables declaration//GEN-END:variables
}
