/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gov.va.semoss.ui.components.insight.manager;

import gov.va.semoss.rdf.engine.api.IEngine;
import gov.va.semoss.rdf.engine.api.WriteableInsightManager;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author ryan
 */
public class InsightManagerPanel extends javax.swing.JPanel {
	private WriteableInsightManager wim;
	private final InsightTreeModel model = new InsightTreeModel();
	
	/**
	 * Creates new form InsightManagerPanel
	 */
	public InsightManagerPanel() {
		initComponents();
	}

	public void refresh( IEngine engine ){
		if( null != wim ){
			wim.release();
		}
		
		wim = engine.getWriteableInsightManager();
		model.refresh( wim );
		
		DefaultMutableTreeNode root
				= DefaultMutableTreeNode.class.cast( tree.getModel().getRoot() );
		
		for ( int i = 0; i < tree.getRowCount(); i++ ) {
			tree.expandRow( i );
		}
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings( "unchecked" )
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jSplitPane1 = new javax.swing.JSplitPane();
    jScrollPane1 = new javax.swing.JScrollPane();
    tree = new javax.swing.JTree();

    jSplitPane1.setDividerLocation(250);

    tree.setModel(model);
    tree.setShowsRootHandles(true);
    jScrollPane1.setViewportView(tree);

    jSplitPane1.setLeftComponent(jScrollPane1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JSplitPane jSplitPane1;
  private javax.swing.JTree tree;
  // End of variables declaration//GEN-END:variables
}
