/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gov.va.semoss.ui.components.insight.manager;

import gov.va.semoss.om.Perspective;

/**
 *
 * @author ryan
 */
public class PerspectivePanel extends DataPanel<Perspective> {

	/**
	 * Creates new form PerspectivePanel
	 */
	public PerspectivePanel() {
		initComponents();
		
		listenTo( perspectiveDesc );
		listenTo( perspectiveName );		
	}

	@Override
	public void isetElement( Perspective p ) {
		perspectiveName.setText( p.getLabel() );
		perspectiveDesc.setText( p.getDescription() );
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings( "unchecked" )
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    perspectiveName = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    jScrollPane6 = new javax.swing.JScrollPane();
    perspectiveDesc = new javax.swing.JTextArea();

    jLabel1.setText("Perspective Name");

    jLabel4.setText("Description");

    perspectiveDesc.setColumns(20);
    perspectiveDesc.setLineWrap(true);
    perspectiveDesc.setRows(5);
    perspectiveDesc.setWrapStyleWord(true);
    jScrollPane6.setViewportView(perspectiveDesc);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(perspectiveName)
          .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(perspectiveName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel4)
          .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(116, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JScrollPane jScrollPane6;
  private javax.swing.JTextArea perspectiveDesc;
  private javax.swing.JTextField perspectiveName;
  // End of variables declaration//GEN-END:variables

	@Override
	public void updateElement( Perspective p ){
		p.setLabel( perspectiveName.getText() );
		p.setDescription( perspectiveDesc.getText() );
	}
}
